version: "3"

services:
  reverse-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - dev
  php:
    build: ./services/php/.
    restart: always
    environment:
      VIRTUAL_HOST: php.local
    volumes:
      - ./services/php/src:/var/www/html/php/public
    networks:
      - dev
  mysql:
    image: mysql:8.0.30
    restart: always
    environment:
      TZ: Europe/London
      VIRTUAL_HOST: mysql.local
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    ports:
      - 3306:3306
    volumes:
      - ./services/mysql/my.cnf:/etc/mysql/my.cnf
      - ./services/mysql/dumps:/docker-entrypoint-initdb.d
    networks:
      - dev
  adminer:
    build: ./services/adminer/.
    restart: always
    environment:
      VIRTUAL_HOST: adminer.local
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DESIGN: konya
    networks:
      - dev
  mongodb:
    image: mongo
    restart: always
    environment:
      VIRTUAL_HOST: ${MONGO_HOST}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - 27017:27017
    networks:
      - dev
    volumes:
      - ./services/mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./services/mongodb/mongod.conf:/etc/mongod.conf

networks:
  dev:
    external: true
